<a href="https://colab.research.google.com/github/leburik-1/machine_learning/blob/main/audio_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import torch
import requests
import imageio
import os

In [ ]:
url = "https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-dog/bobby.jpg"
file_name = "bobby.jpg"

# Download the image using streaming
response = requests.get(url, stream=True)
response.raise_for_status()

# save the image
with open(file_name, "wb") as file:
  for chunk in response.iter_content(chunk_size=8192): # Efficient chunk download
    file.write(chunk)

img_arr = imageio.imread(file_name)
img_arr.shape
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

batch_size = 3
batch = torch.zeros(batch_size, 3, 256,256,dtype=torch.uint8)

data_dir = "/image-cats"
os.makedirs(data_dir, exist_ok=True)

filenames = [
    "cat1.png",
    "cat2.png",
    "cat3.png"
]

base_url = "https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch4/image-cats/"

# download all files
for filename in filenames:
  url = base_url + filename
  response = requests.get(url, stream=True)

  if response.status_code == 200:
    with open(os.path.join(data_dir, filename), "wb") as file:
      for chunk in response.iter_content(1024):
        file.write(chunk)
    print(f"Downloaded: {filename}")
  else:
    print(f"Failed to download: {filename}")



filenames = [name for name in os.listdir(data_dir) if name.endswith(".png")]
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

for filename in filenames:
  img_arr = imageio.imread(os.path.join(data_dir, filename))
  img_t = torch.from_numpy(img_arr)
  # rearrange channes (H, W, C) -> (C, H, W)
  img_t = img_t.permute(2,0,1)
  img_t = img_t[:3]  # keep only first 3 channels (ignore alpha)
  batch.append(img_t)

batch

# normalization
n_channels = batch.shape[1]
for c in range(n_channels):
  mean = torch.mean(batch[:, c])
  std = torch.std(batch[:, c])
  batch[:, c] = (batch[:, c] - mean) / std


<ipython-input-17-537ca935b2ee>:13: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(file_name)


Downloaded: cat1.png
Downloaded: cat2.png
Downloaded: cat3.png


<ipython-input-17-537ca935b2ee>:51: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


AttributeError: 'Tensor' object has no attribute 'append'

In [ ]:
!apt-get install subversion -q

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2
Suggested packages:
  db5.3-util libapache2-mod-svn subversion-tools
The following NEW packages will be installed:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2 subversion
0 upgraded, 6 newly installed, 0 to remove and 29 not upgraded.
Need to get 2,672 kB of archives.
After this operation, 10.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libapr1 amd64 1.7.0-8ubuntu0.22.04.2 [108 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libaprutil1 amd64 1.6.1-5ubuntu4.22.04.2 [92.8 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libserf-1-1 amd64 1.3.9-10ubuntu2 [50.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libutf8proc2 amd64 2.7.0-3 [73.9 kB]
Get:5 http://archive.ubuntu.com/ubun

Type 'svn help' for usage.


In [ ]:
!svn export https://github.com/deep-learning-with-pytorch/dlwpt-code/trunk/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083


svn: E170013: Unable to connect to a repository at URL 'https://github.com/deep-learning-with-pytorch/dlwpt-code/trunk/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083'
svn: E160013: '/deep-learning-with-pytorch/dlwpt-code/trunk/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083' path not found


In [ ]:
!svn export https://github.com/deep-learning-with-pytorch/dlwpt-code/tree/master/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083

svn: E170013: Unable to connect to a repository at URL 'https://github.com/deep-learning-with-pytorch/dlwpt-code/tree/master/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083'
svn: E160013: '/deep-learning-with-pytorch/dlwpt-code/tree/master/data/p1ch4/volumetric-dicom/2-LUNG%203.0%20%20B70f-04083' path not found


In [ ]:
!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code.git

Cloning into 'dlwpt-code'...
remote: Enumerating objects: 706, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 706 (delta 107), reused 87 (delta 87), pack-reused 556 (from 2)
Receiving objects: 100% (706/706), 175.17 MiB | 20.53 MiB/s, done.
Resolving deltas: 100% (319/319), done.
Updating files: 100% (228/228), done.


In [ ]:
!ls

bobby.jpg  dlwpt-code  sample_data


In [ ]:
!cd dlwpt-code

In [ ]:
!ls

bobby.jpg  dlwpt-code  sample_data


In [ ]:
source_dir = "dlwpt-code/tree/master/data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083"
destination_dir = "LUNG_DATA"

import glob

base_dir = "dlwpt-code/data/p1ch4/volumetric-dicom"
folders = glob.glob(base_dir + "/*")

print("Found directories:", folders)


Found directories: []


In [ ]:
!wget -o dlwpt-code.zip https://github.com/deep-learning-with-pytorch/dlwpt-code/archive/refs/heads/master.zip

In [ ]:
!curl -L -o dlwpt-code.zip https://github.com/deep-learning-with-pytorch/dlwpt-code/archive/refs/heads/master.zip


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  171M    0  171M    0     0  11.1M      0 --:--:--  0:00:15 --:--:-- 11.0M


In [ ]:
!unzip -q dlwpt-code.zip -d .

In [ ]:
!ls

bobby.jpg  dlwpt-code  dlwpt-code-master  dlwpt-code.zip  LUNG_DATA  master.zip  sample_data


In [ ]:
%cd dlwpt-code-master

/content/dlwpt-code-master


In [ ]:
!ls -R data/p1ch4/volumetric-dicom

data/p1ch4/volumetric-dicom:
'2-LUNG 3.0  B70f-04083'

'data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083':
000000.dcm  000013.dcm	000026.dcm  000039.dcm	000052.dcm  000065.dcm	000078.dcm  000091.dcm
000001.dcm  000014.dcm	000027.dcm  000040.dcm	000053.dcm  000066.dcm	000079.dcm  000092.dcm
000002.dcm  000015.dcm	000028.dcm  000041.dcm	000054.dcm  000067.dcm	000080.dcm  000093.dcm
000003.dcm  000016.dcm	000029.dcm  000042.dcm	000055.dcm  000068.dcm	000081.dcm  000094.dcm
000004.dcm  000017.dcm	000030.dcm  000043.dcm	000056.dcm  000069.dcm	000082.dcm  000095.dcm
000005.dcm  000018.dcm	000031.dcm  000044.dcm	000057.dcm  000070.dcm	000083.dcm  000096.dcm
000006.dcm  000019.dcm	000032.dcm  000045.dcm	000058.dcm  000071.dcm	000084.dcm  000097.dcm
000007.dcm  000020.dcm	000033.dcm  000046.dcm	000059.dcm  000072.dcm	000085.dcm  000098.dcm
000008.dcm  000021.dcm	000034.dcm  000047.dcm	000060.dcm  000073.dcm	000086.dcm
000009.dcm  000022.dcm	000035.dcm  000048.dcm	000061.dcm  000074.dcm	000087

In [ ]:
import imageio
import csv
import numpy as np

In [ ]:
dir_path = "data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083"
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/99 files (1.0%)99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 59/99  (59.6%)99/99  (100.0%)


(99, 512, 512)

In [ ]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 0)
vol.shape

torch.Size([1, 99, 512, 512])

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
file_name = "winequality-white.csv"

response = requests.get(url, stream=True)

with open(file_name, "wb") as file:
  for chunk in response.iter_content(chunk_size=8192):
    file.write(chunk)

wineq_numpy = np.loadtxt(file_name, dtype=np.float32, delimiter=";", skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [30]:
col_list = next(csv.reader(open(file_name), delimiter=";"))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [ ]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [11]:
data = wineq[:, :-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [ ]:
target = wineq[:, -1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [ ]:
target = wineq[:, -1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [15]:
target.shape
# target_unsqueezed = target.unsqueeze(1)
# target_unsqueezed.shape

torch.Size([4898])

In [16]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [17]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [18]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [19]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [20]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [29]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]

torch.Size([1060, 11])

In [31]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
  print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [32]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:, 6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)
predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [33]:
actual_indexes = target > 5
actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [34]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches / n_predicted, n_matches / n_actual

(2018, 0.74000733406674, 0.6193984039287906)

In [35]:
!curl -L -o bike_sharing.zip  https://archive.ics.uci.edu/static/public/275/bike+sharing+dataset.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  273k    0  273k    0     0   162k      0 --:--:--  0:00:01 --:--:--  162k


In [38]:
!unzip -q bike_sharing.zip -d .

replace ./Readme.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ./day.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ./hour.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [40]:
!unzip -q bike_sharing.zip -d .

replace ./Readme.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
replace ./day.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
replace ./hour.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
error:  invalid response [{ENTER}]
replace ./hour.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N


In [41]:
!ls

bike_sharing.zip  day.csv  hour.csv  Readme.txt  sample_data  winequality-white.csv


In [46]:
bikes_numpy = np.loadtxt("hour.csv",
                        dtype=np.float32,
                        delimiter=",",
                        skiprows=1,
                        converters={1: lambda x: float(x[8:10])})
bikes = torch.from_numpy(bikes_numpy)
bikes.shape, bikes.stride()

(torch.Size([17379, 17]), (17, 1))

In [61]:
valid_hours = 724 * 24
bikes_trimmed = bikes[:valid_hours] # keep only 17376 rows
daily_bikes = bikes_trimmed.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()
bikes_trimmed.shape

torch.Size([17376, 17])

In [57]:
first_day = bikes_trimmed[:24].long()
first_day.shape
weather_onehot = torch.zeros(first_day.shape[0], 4)
first_day[:, 9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [58]:
  weather_onehot.scatter_(dim=1,
                          index=first_day[:, 9].unsqueeze(1).long() - 1,
                          value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [59]:
torch.cat((bikes_trimmed[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [60]:
bikes_onehot = torch.zeros(bikes_trimmed.shape[0],
                           4, bikes_trimmed.shape[2])
bikes_onehot.shape

IndexError: tuple index out of range

In [80]:
url = "https://www.gutenberg.org/files/1342/1342-0.txt"
file_name = "frankenstein.txt"

response = requests.get(url, stream=True)

with open(file_name, "wb") as file:
  for chunk in response.iter_content(chunk_size=8192):
    file.write(chunk)

with open(file_name, encoding="utf8") as f:
  text = f.read()

lines = text.split("\n")
letter_t = torch.zeros(len(lines), 128)
letter_t.shape
line = lines[200]
line

'snarling invective, but to gentle and oblique satire. If cynicism means'

In [81]:
for i, letter in enumerate(line.lower().strip()):
  letter_index = ord(letter) if ord(letter) < 128 else 0
  letter_t[i][letter_index] = 1

In [86]:
def clean_words(input_str):
  punctuation = '.,;:"!?”“_-'
  word_list = input_str.lower().replace('\n', ' ').split()
  word_list = [word.strip(punctuation) for word in word_list]
  return word_list

words_in_line = clean_words(line)
word_list = sorted(set(clean_words(text)))
word2index_dict = { word: i for (i,word) in enumerate(word_list) }
len(word2index_dict), word2index_dict['impossible']

(7465, 3455)

In [88]:
  len(words_in_line), len(word2index_dict)

(11, 7465)

In [91]:
word_t = torch.zeros(len(words_in_line),len(word2index_dict))

for i, word in enumerate(words_in_line):
  word_index = word2index_dict[word]
  word_t[i][word_index] = 1
  print('{:2} {:4} {}'.format(i, word_index, word))

print(word_t.shape)

 0 6143 snarling
 1 3725 invective
 2  992 but
 3 6680 to
 4 2935 gentle
 5  439 and
 6 4578 oblique
 7 5795 satire
 8 3378 if
 9 1670 cynicism
10 4213 means
torch.Size([11, 7465])


In [92]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.


In [93]:
%cd /content

/content


In [94]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [95]:
!git remote add origin https://github.com/karolpiczak/ESC-50.git

In [96]:
!git config core.sparseCheckout true

In [97]:
!echo "audio" >> .git/info/sparse-checkout

In [98]:
!git pull origin master

remote: Enumerating objects: 4199, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 4199 (delta 40), reused 38 (delta 18), pack-reused 4136 (from 1)
Receiving objects: 100% (4199/4199), 878.79 MiB | 28.73 MiB/s, done.
Resolving deltas: 100% (287/287), done.
From https://github.com/karolpiczak/ESC-50
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Updating files: 100% (2000/2000), done.


In [99]:
!ls -R audio

audio:
1-100032-A-0.wav   2-100648-A-43.wav  3-100018-A-18.wav  4-102844-A-49.wav  5-103415-A-2.wav
1-100038-A-14.wav  2-100786-A-1.wav   3-100024-A-27.wav  4-102844-B-49.wav  5-103416-A-2.wav
1-100210-A-36.wav  2-101676-A-10.wav  3-100024-B-27.wav  4-102844-C-49.wav  5-103418-A-2.wav
1-100210-B-36.wav  2-102414-A-17.wav  3-101381-A-33.wav  4-102871-A-42.wav  5-103420-A-2.wav
1-101296-A-19.wav  2-102414-B-17.wav  3-101381-B-33.wav  4-107117-A-33.wav  5-103421-A-2.wav
1-101296-B-19.wav  2-102414-C-17.wav  3-102583-A-49.wav  4-107120-A-33.wav  5-103422-A-2.wav
1-101336-A-30.wav  2-102414-D-17.wav  3-102583-B-49.wav  4-107122-A-33.wav  5-117118-A-42.wav
1-101404-A-34.wav  2-102414-E-17.wav  3-102583-C-49.wav  4-108352-A-33.wav  5-117120-A-42.wav
1-103298-A-9.wav   2-102414-F-17.wav  3-102908-A-4.wav	 4-111671-A-42.wav  5-117122-A-42.wav
1-103995-A-30.wav  2-102414-G-17.wav  3-103050-A-19.wav  4-111671-B-42.wav  5-117250-A-2.wav
1-103999-A-30.wav  2-102435-A-37.wav  3-103051-A-19.wav  4-11

In [4]:
import scipy.io.wavfile as wavfile

freq, waveform_arr = wavfile.read('audio/1-100038-A-14.wav')
waveform = torch.from_numpy(waveform_arr).float()
waveform.shape

FileNotFoundError: [Errno 2] No such file or directory: 'audio/1-100038-A-14.wav'

In [3]:
from scipy import signal
f_arr, t_arr , spec_arr = signal.spectrogram(waveform_arr,freq)
sp_mono = torch.from_numpy(spec_arr)
sp_mono.shape

NameError: name 'waveform_arr' is not defined

In [2]:
# if we got two channels
sp_left = sp_right = spec_arr
sp_left_t = torch.from_numpy(sp_left)
sp_right_t = torch.from_numpy(sp_right)

sp_t = torch.stack((sp_left_t, sp_right_t), dim=0)
sp_t.shape

NameError: name 'spec_arr' is not defined